// Generated by CoffeeScript 1.11.1
(function() {
  module.exports.addStudent = function(permissions, profile_st, groups) {
    var addStudent;
    return addStudent = function(aData, callback, error) {
      var addData, getPermissions;
      console.log(aData);
      getPermissions = function() {
        return new Promise(resolve, reject)(function() {
          return permissions.addData({
            login: aData.login,
            password: aData.password,
            permission: 'student'
          }, (function(permission) {
            console.log(1);
            return resolve(permission);
          }), (function(error) {
            return console.log(2);
          }));
        });
      };
      addData = function() {
        return new Promise(resolve, reject)(function() {
          return groups.addData({
            course: aData.course,
            squad: aData.squad
          }, (function(group) {
            return resolve(group);
          }), error);
        });
      };
      return Promise.all([getPermissions, addData]).then(function(data) {
        return profile_st.addData({
          student_id: data[0]._id,
          group_id: data[1]._id
        }, (function(result) {
          return callback(result);
        }), error);
      });
    };
  };

}).call(this);

//# sourceMappingURL=addStudent.js.map
