// Generated by CoffeeScript 1.11.1
(function() {
  module.exports.getMarks = function(discipline, marks) {
    var getMarks;
    return getMarks = function(aData, callback, error) {
      return marks.get({
        student_id: aData.student_id
      }, function(data) {
        var average, count, rows;
        rows = [];
        count = 0;
        average = 0;
        return data.forEach(function(mark) {
          return discipline.get({
            discipline_id: mark.discipline_id
          }, (function(_this) {
            return function(name) {
              var status;
              status = false;
              rows.forEach(function(row) {
                if (row.nameSubject === name) {
                  status = true;
                  row['senestr' + mark.term] = mark.term;
                  return average += Number(mark.mark);
                }
              });
              if (!status) {
                rows.push({
                  nameSubject: name
                });
                rows[rows.length - 1]['semestr' + mark.term] = mark.mark;
                average += Number(mark.mark);
              }
              ++count;
              if (data.length === count) {
                return callback(rows, average / count);
              } else {
                return null;
              }
            };
          })(this), error);
        });
      }, error);
    };
  };

}).call(this);

//# sourceMappingURL=getMarks.js.map
