// Generated by CoffeeScript 1.11.1
(function() {
  module.exports.getStandarts = function(standarts, standarts_st) {
    var getStandarts;
    return getStandarts = function(aData, callback, error) {
      return standarts_st.get({
        student_id: aData.student_id
      }, function(data) {
        var count, rows;
        rows = [];
        count = 0;
        return data.forEach(function(standart) {
          return standart.get({
            standart_id: standart.standart_id
          }, function(name) {
            var status;
            status = false;
            rows.forEach(function(row) {
              if (row.nameStandart === name) {
                status = true;
                return row['semestr' + standart.term] = standart.standart;
              }
            });
            if (!status) {
              rows.push({
                nameStandart: name
              });
              rows[rows.length - 1]['semestr' + standart.term] = standart.standart;
            }
            ++count;
            if (data.length === count) {
              return callback(rows);
            }
          }, error);
        });
      }, error);
    };
  };

}).call(this);

//# sourceMappingURL=getStandarts.js.map
