// Generated by CoffeeScript 1.11.1
(function() {
  module.exports.updateMarks = function(marks) {
    var updateMarks;
    return updateMarks = function(aData, callback, error) {
      var success;
      success = true;
      aData.req.forEach((function(_this) {
        return function(mark) {
          return marks.updateData(JSON.parse(mark), (function(res) {}), (function(error) {
            return success = false;
          }));
        };
      })(this));
      if (success) {
        return callback(true);
      } else {
        return error(false);
      }
    };
  };

}).call(this);

//# sourceMappingURL=updateMarks.js.map
