// Generated by CoffeeScript 1.11.1
(function() {
  module.exports.updateMarks = function(marks) {
    var updateMarks;
    return updateMarks = function(aData, callback, error) {
      var success;
      success = true;
      aData.req.forEach((function(_this) {
        return function(mark) {
          var err;
          try {
            return marks.updateData(mark, (function(res) {}), (function(error) {
              return success = false;
            }));
          } catch (error1) {
            err = error1;
            return error(err);
          }
        };
      })(this));
      if (success) {
        return callback(true);
      } else {
        return error(false);
      }
    };
  };

}).call(this);

//# sourceMappingURL=updateMarks.js.map
