// Generated by CoffeeScript 1.11.1
(function() {
  var Standart, Standarts, StandartsModel, mongoose;

  mongoose = require('mongoose');

  Standarts = mongoose.Schema;

  Standart = new Standarts({
    standart_name: {
      type: String,
      required: true
    }
  });

  StandartsModel = mongoose.model('Standart', Standart);

  module.exports.StandartsModel = StandartsModel;

}).call(this);

//# sourceMappingURL=Standarts.js.map
