// Generated by CoffeeScript 1.11.1
(function() {
  var Discipline, DisciplineModel, discipline, mongoose;

  mongoose = require('mongoose');

  Discipline = mongoose.Schema;

  discipline = new Discipline({
    discipline_name: {
      type: String,
      required: true
    },
    teacher_id: {
      type: String,
      required: false
    }
  });

  DisciplineModel = mongoose.model('discipline', discipline);

  module.exports.DisciplineModel = DisciplineModel;

}).call(this);

//# sourceMappingURL=Discipline.js.map
